name: Build & Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    
    - name: Install packages
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    
    - name: Build project
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build
    
    - name: Run tests
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: test

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./build
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
      # run: |
      #   git config --global user.email ${{ secrets.DEPLOY_EMAIL }}
      #   git config --global user.name ${{ secrets.DEPLOY_USERNAME }}
      #   git remote set-url origin https://${{ secrets.DEPLOY_ACCESS_TOKEN }}@github.com/${{ secrets.DEPLOY_USERNAME }}/frontend.git
      #   npm run deploy